<a href="https://colab.research.google.com/github/jfogarty/machine-learning-intro-workshop/blob/master/notebooks/numpy_data_structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Vectors, Matrices, and Arrays

- From [Machine Learning with Python Cookbook](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html) by [Chris Albon](https://chrisalbon.com/) [[Github/notes](https://github.com/chrisalbon/notes)], published by [O'Reilly Safari](https://www.oreilly.com).

Updated by [John Fogarty](https://github.com/jfogarty) for Python 3.6 and [Base2 MLI](https://github.com/base2solutions/mli).


## 1.0 Introduction

NumPy is the foundation of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors. While NumPy is not the focus of this book, it will show up frequently throughout the following chapters. This chapter covers the most common NumPy operations we are likely to run into while working on machine learning workflows.

## 1.1 Creating a Vector
### Problem
You need to create a vector.

### Solution
Use NumPy to create a one-dimensional array:

In [15]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print("My Row: ") 
print(vector_row)

print("my Column: ")
print(vector_column)


My Row: 
[1 2 3]
my Column: 
[[1]
 [2]
 [3]]


### Discussion

NumPy’s main data structure is the multidimensional array. To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

### See Also
- [Vectors, Math Is Fun](http://bit.ly/2FB5q1v)

- [Euclidean vector, Wikipedia](http://bit.ly/2FtnRoL)


## 1.2 Creating a Matrix
### Problem
You need to create a matrix.

### Solution
Use NumPy to create a two-dimensional array:

In [20]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

### Discussion
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s).

NumPy actually has a dedicated matrix data structure:

In [19]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

However, the matrix data structure is **not recommended** for two reasons. First, arrays are the de facto standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not matrix objects.

### See Also
- [Matrix, Wikipedia](http://bit.ly/2Ftnevp)

- [Matrix, Wolfram MathWorld](http://bit.ly/2Fut7IJ)

## 1.3 Creating a Sparse Matrix
### Problem
Given data with very few nonzero values, you want to efficiently represent it.

### Solution
Create a sparse matrix:

In [0]:
# Load libraries
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

### Discussion
A frequent situation in machine learning is having a huge amount of data; however, most of the elements in the data are zeros. For example, imagine a matrix where the columns are every movie on Netflix, the rows are every Netflix user, and the values are how many times a user has watched that particular movie. This matrix would have tens of thousands of columns and millions of rows! However, since most users do not watch most movies, the vast majority of elements would be zero.

Sparse matrices only store nonzero elements and assume all other values will be zero, leading to significant computational savings. In our solution, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored:

In [8]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in *compressed sparse row* (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [22]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

As mentioned, there are many different types of sparse matrices, such as compressed sparse column, list of lists, and dictionary of keys. While an explanation of the different types and their implications is outside the scope of this book, it is worth noting that while there is no “best” sparse matrix type, there are meaningful differences between them and we should be conscious about why we are choosing one type over another.

### See Also
- [Sparse matrices, SciPy documentation](http://bit.ly/2HReBZR)

- [101 Ways to Store a Sparse Matrix](http://bit.ly/2HS43cI)

## 1.4 Selecting Elements
### Problem
You need to select one or more elements in a vector or matrix.

### Solution
NumPy’s arrays make that easy:

In [61]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [25]:
# Select second row, second column
matrix[1,1]

5

### Discussion
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [27]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [28]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [29]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [30]:
# Select the last element
vector[-1]

6

In [31]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix
### Problem
You want to describe the shape, size, and dimensions of the matrix.

### Solution
Use shape, size, and ndim:

In [33]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

(3, 4)

In [34]:
# View number of elements (rows * columns)
matrix.size

12

In [35]:
# View number of dimensions
matrix.ndim

2

Discussion
This might seem basic (and it is); however, time and again it will be valuable to check the shape and size of an array both for further calculations and simply as a gut check after some operation.

## 1.6 Applying Operations to Elements
### Problem
You want to apply some function to multiple elements in an array.

### Solution
Use NumPy’s vectorize:

In [36]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### Discussion
NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

In [37]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Finding the Maximum and Minimum Values
### Problem
You need to find the maximum or minimum value in an array.

### Solution
Use NumPy’s max and min:

In [38]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [39]:
# Return minimum element
np.min(matrix)

1

### Discussion
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:

In [0]:
# Find maximum element in each column
np.max(matrix, axis=0)

In [0]:
# Find maximum element in each row
np.max(matrix, axis=1)

## 1.8 Calculating the Average, Variance, and Standard Deviation
### Problem
You want to calculate some descriptive statistics about an array.

### Solution
Use NumPy’s mean, var, and std:

In [48]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [47]:
# Return variance
np.var(matrix)

11.916666666666666

In [46]:
# Return standard deviation
np.std(matrix)

3.452052529534663

### Discussion
Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis:

In [45]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([5.5, 6.5, 7.5])

## 1.9 Reshaping Arrays
### Problem
You want to change the shape (number of rows and columns) of an array without changing the element values.

### Solution
Use NumPy’s reshape:

In [51]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Discussion
reshape allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns. The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., the same size). We can see the size of a matrix using size:

In [52]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [53]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [0]:
matrix.reshape(12)

## 1.10 Transposing a Vector or Matrix
### Problem
You need to transpose a vector or matrix.

### Solution
Use the T method:

In [54]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Discussion
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values:

In [57]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [58]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix
### Problem
You need to transform a matrix into a one-dimensional array.

### Solution
Use flatten:

In [65]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Discussion
flatten is a simple method to transform a matrix into a one-dimensional array. Alternatively, we can use reshape to create a row vector:

In [67]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Explore binary operations on row vectors with one dimensional arrays.

In [68]:
matrix.reshape(1, -1) == matrix.flatten()

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [69]:
matrix.flatten() == matrix.reshape(1, -1)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [70]:
matrix.flatten() * matrix.reshape(1, -1)

array([[ 1,  4,  9, 16, 25, 36, 49, 64, 81]])

In [71]:
matrix.reshape(1, -1)[0] == matrix.flatten()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [72]:
matrix.reshape(1, -1).shape

(1, 9)

In [73]:
matrix.reshape(1, -1)[0].shape

(9,)

In [74]:
matrix.flatten().shape

(9,)

## 1.12 Finding the Rank of a Matrix
### Problem
You need to know the rank of a matrix.

### Solution
Use NumPy’s linear algebra method matrix_rank:

In [75]:
# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

### Discussion
The rank of a matrix is the dimensions of the vector space spanned by its columns or rows. Finding the rank of a matrix is easy in NumPy thanks to matrix_rank.

### See Also
- [The Rank of a Matrix, CliffsNotes](http://bit.ly/2HUzkMs)

## 1.13 Calculating the Determinant
### Problem
You need to know the determinant of a matrix.

### Solution
Use NumPy’s linear algebra method det

In [76]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

In [77]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 6, 6],
                   [4, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

-6.0

### Discussion
It can sometimes be useful to calculate the determinant of a matrix. NumPy makes this easy with det.

### See Also
- [The determinant | Essence of linear algebra, chapter 5](http://bit.ly/2FA6ToM)

- [Determinant, Wolfram MathWorld](http://bit.ly/2FxSUzC)

## 1.14 Getting the Diagonal of a Matrix
## Problem
You need to get the diagonal elements of a matrix.

### Solution
Use diagonal:

In [78]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

### Discussion
NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:

In [79]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [80]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

## 1.15 Calculating the Trace of a Matrix
### Problem
You need to calculate the trace of a matrix.

### Solution
Use trace:

In [81]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()

14

### Discussion
The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. We can also return the diagonal of a matrix and calculate its sum:

In [82]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

### See Also
- [The Trace of a Square Matrix](http://bit.ly/2FunM45)

## 1.16 Finding Eigenvalues and Eigenvectors
Problem
You need to find the eigenvalues and eigenvectors of a square matrix.

Solution
Use NumPy’s linalg.eig:

In [0]:
# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [85]:
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [86]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### Discussion
Eigenvectors are widely used in machine learning libraries. Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction). More formally:

$$A v = λ v$$

where $A$ is a square matrix, $λ$ contains the eigenvalues and $v$ contains the eigenvectors. In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix.

### See Also
- [Eigenvectors and Eigenvalues Explained Visually, Setosa.io](http://bit.ly/2Hb32LV)

- [Eigenvectors and eigenvalues | Essence of linear algebra, Chapter 10](http://bit.ly/2HeGppK)

## 1.17 Calculating Dot Products
### Problem
You need to calculate the dot product of two vectors.

### Solution
Use NumPy’s dot:

In [88]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

### Discussion
The dot product of two vectors, a and b, is defined as:

$$
\sum_{i=1}^{n} a_i b_i
$$

where $a_i$ is the ith element of vector a. We can use NumPy’s dot class to calculate the dot product. Alternatively, in Python 3.5+ we can use the new @ operator:

In [89]:
# Calculate dot product
vector_a @ vector_b

32

### See Also
- [Vector dot product and vector length, Khan Academy](http://bit.ly/2Fr0AUe)

- [Dot Product, Paul’s Online Math Notes](http://bit.ly/2HgZHLp)

## 1.18 Adding and Subtracting Matrices
### Problem
You want to add or subtract two matrices.

### Solution
Use NumPy’s add and subtract:

In [90]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [91]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

### Discussion
Alternatively, we can simply use the + and - operators:

In [92]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matrices
### Problem
You want to multiply two matrices.

### Solution
Use NumPy’s dot:

In [93]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

Discussion
Alternatively, in Python 3.5+ we can use the @ operator:

In [94]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

If we want to do element-wise multiplication, we can use the * operator:

In [95]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

### See Also
- [Array vs. Matrix Operations, MathWorks](http://bit.ly/2FtpXVr)

## 1.20 Inverting a Matrix
### Problem
You want to calculate the inverse of a square matrix.

### Solution
Use NumPy’s linear algebra inv method:

In [96]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

### Discussion
The inverse of a square matrix, $A$, is a second matrix $A^{–1}$, such that:

$$A A^{-1} = I$$

where $I$ is the identity matrix. In NumPy we can use linalg.inv to calculate $A^{–1}$ if it exists. To see this in action, we can multiply a matrix by its inverse and the result is the identity matrix:

In [97]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

### See Also
- [Inverse of a Matrix](http://bit.ly/2Fzf0BS)

## 1.21 Generating Random Values
### Problem
You want to generate pseudorandom values.

### Solution
Use NumPy’s random:

In [98]:
# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

### Discussion
NumPy offers a wide variety of means to generate random numbers, many more than can be covered here. 

Note that if `np.random.seed` is `None`, then `RandomState` will try to read data from /dev/urandom (or the Windows analogue) if available or seed from the clock otherwise, rather than using a repeatable pseudo random sequence.

In our solution we generated floats; however, it is also common to generate integers:

In [99]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

Alternatively, we can generate numbers by drawing them from a distribution:

In [100]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [101]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [102]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

## Setting the random seed

Finally, it can sometimes be useful to return the same random numbers multiple times to get predictable, repeatable results. We can do this by setting the “seed” (an integer) of the pseudorandom generator. Random processes with the same seed will always produce the same output. 



In [104]:
# Set seed
np.random.seed(123)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.69646919, 0.28613933, 0.22685145])

In [105]:
# Do it again
np.random.seed(123)
np.random.random(3)

array([0.69646919, 0.28613933, 0.22685145])

### End of notebook.